name: brandboostformula
favicon: null
layout_spectrum: 0.56758
typography_spectrum: 0.42348
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#b5b5b5'
    - '#ffffff'
    - '#fed700'
    - '#505050'
    - '#1d1d1d'
  brandStrength: 0.6875
  lightness: 0.4523331350646913
  saturation: 0.7272934697102755
  rhythmicContrast: 0.2771404522936791
purpose: []
